
//array of sentences
String []sentences={
  "What is the meaning of life", 
  "Are we just living in a simulation", 
  "What are the chances of a successful career", 
  "am I wasting my life", 
  "I love my cat", 
  "Remember that one time I replied you too to the employee at cinema.", 
  "I might end up alone and I’m almost okay with that, and that frightens me", 
  "*argument playback*", 
  "Should I just get up and watch tiktoks", 
  "I’m lonely", 
  "I hope the jinns in my room aren’t mad at me", 
  "I want a hug", 
  "It’s cold", 
  "Is my best not good enough", 
  "It could all go away at any moment", 
  "What if…", 
  "Will my parents continue to control every aspect of my life forever", 
  "I hate how I don’t really know if anything is real", 
  "Am I going to fail in life?", 
  "*problem solving my unfinished code", 
  "To eat or not to eat ramen", 
  "I did nothing productive today", 
  "I should drop out and become a ********", 
  "Why didn't rose leave room for Jack?", 
  "Am I real?", 
  "Is there a way to die without pain?", 
  "I'll never have the time to play all the good video games", 
  "Why are humans a thing", 
  "*endless potential of memes*", 
  "*to do list*", 
  "Where will I continue in life?", 
  "Why can't I fall asleep?"};
